export const deliveryResourceOptions = {
  // List
  listProperties: [
    'id',
    'userId',
    'title',
    'code',
    'fid',
    'invoice',
    'level',
    'estimate',
    'time',
    'isComplete',
    'nameSender',
    'callOffice',
    'callDriver',
    'nameDriver',
    'addressReceiver',
    'nameReceiver',
    'isTrackingRegistered',
    'createdAt',
    'updatedAt',
  ],

  // Show
  showProperties: [
    'id',
    'userId',
    'title',
    'code',
    'fid',
    'invoice',
    'level',
    'estimate',
    'time',
    'isComplete',
    'nameSender',
    'callOffice',
    'callDriver',
    'nameDriver',
    'addressReceiver',
    'nameReceiver',
    'isTrackingRegistered',
    'createdAt',
    'updatedAt',
  ],

  // Edit
  editProperties: [
    'userId',
    'title',
    'code',
    'fid',
    'invoice',
    'level',
    'estimate',
    'time',
    'isComplete',
    'nameSender',
    'callOffice',
    'callDriver',
    'nameDriver',
    'addressReceiver',
    'nameReceiver',
    'isTrackingRegistered',
  ],
};
